// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admission/report-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admission"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sDate",
                        "name": "sDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dateType",
                        "name": "dateType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admission/report/day": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admission"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "days",
                        "name": "days",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sHospitalCode",
                        "name": "sHospitalCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admission/report/month": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admission"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "months",
                        "name": "months",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sHospitalCode",
                        "name": "sHospitalCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/appointment/statistics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/appointment/statistics-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Appointment"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sDate",
                        "name": "sDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/attendance/outpatient-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sDate",
                        "name": "sDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dateType",
                        "name": "dateType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/attendance/outpatient/day": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "days",
                        "name": "days",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sHospitalCode",
                        "name": "sHospitalCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/attendance/outpatient/month": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "months",
                        "name": "months",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sHospitalCode",
                        "name": "sHospitalCode",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/finance/ar-ageing": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sTopARNum",
                        "name": "sTopARNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COMPANY_ID",
                        "name": "COMPANY_ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/average-los": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/bed-status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/bed-status-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sBedStatus",
                        "name": "sBedStatus",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/demographics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/regadm": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/specialty": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/inpatient/ward-census": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COMPANY_ID",
                        "name": "COMPANY_ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/lab/charges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sRptType",
                        "name": "sRptType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COMPANY_ID",
                        "name": "COMPANY_ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/lab/kpi-statistics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sRptType",
                        "name": "sRptType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COMPANY_ID",
                        "name": "COMPANY_ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/lab/service-cls": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lab"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sRptType",
                        "name": "sRptType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "COMPANY_ID",
                        "name": "COMPANY_ID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/mortality/lookup/gender": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mortality"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/mortality/total-death": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mortality"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sYear",
                        "name": "sYear",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/mortality/total-death-case": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mortality"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sYear",
                        "name": "sYear",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/mortality/total-death-count-gender": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mortality"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sYear",
                        "name": "sYear",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/mortality/total-death-gender": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mortality"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sYear",
                        "name": "sYear",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sGender",
                        "name": "sGender",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/outpatient/attendances": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/outpatient/clinic": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/outpatient/clinic-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sClinicCode",
                        "name": "sClinicCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/outpatient/demographics": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Outpatient"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_user_session_id",
                        "name": "vx_user_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_user_name",
                        "name": "vx_user_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/referral/external": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/referral/external-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sDate",
                        "name": "sDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/referral/internal": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/referral/internal-popup": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Referral"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "sDate",
                        "name": "sDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sType",
                        "name": "sType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_comp_name",
                        "name": "vx_comp_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "vx_environment",
                        "name": "vx_environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/edashboard",
	Schemes:          []string{},
	Title:            "Swagger E-Dashboard API",
	Description:      "E-Dashboard API description.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
